
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";

import React, { useState } from "react";
import AdminShell from "./components_admin/Layout/adminShell";



export const metadata: Metadata = {
  title: "Admin nè",
  description: "Generated by create next app",
};

// 👇 You can't use useState directly in a Server Component like layout.tsx
// So we should avoid toggle state here – keep the sidebar always expanded
export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="mdl-js">
      <body>
        <AntdRegistry>
          <AdminShell>{children}</AdminShell>
        </AntdRegistry>
      </body>
    </html>
  );
}
